### ISSUE TITLE
latest PostgreSQL

### ISSUE THREAD

**Issue by lonnieOST** [EgaLabs/docker-postgresql#1]
Hello,

I came across your repo while looking for a Postgresql server that can be run in a docker container as well as to have installed prgui and pgcrypto extensions.

Also, does your setup support the latest Postgresql 10 server. My understanding is that they are also currently testing version 11 at this moment as well.

Anything that you could do to help would be greatly appreciated
Thanks

**Comment by egasato** [comment]
Hello,

I don't know right now if upgrading the PostgreSQL version will break the build but you can try changing the Dockerfile and see what happens.

Enviado desde ProtonMail móvil

-------- Mensaje original --------

**Comment by lonnieOST** [comment]
Hello,

I actually, just tried the setup that you had at Docker Hub 

https://hub.docker.com/r/egalabs/postgresql/

and it seems to crash.

Is the 9.6.2 and 9.6.2-alpine the highest versions that will function that you have on your Github site?

I need to be able to use phcrypto and pguri for my project.

Thanks

**Comment by lonnieOST** [comment]
Hello,

I'm working on compiling it up for Postgresql 10.5 and it seems to compile just fine.

Now I can try to hand install it on the server (ubuntu 16.04).

Can you please tell me the default past locate in which it installs as I cannot seem to locate that information?

**Comment by egasato** [comment]
Hello,
Maybe I stopped pushing my commits in the middle of a patch or something. If you send me the log maybe I can guess what's the problem. Also, the fact that a Docker Hub let's its users update any image could have affected it; the base image could have changed.

Enviado desde ProtonMail móvil

-------- Mensaje original --------

**Comment by lonnieOST** [comment]
Thanks, but I have solved it all.

I was able to compile up t he pguri extension and install it in Postgresql 10.5 with no problems.

We can close this ticket now.
Cheers
